### ISSUE TITLE
Not working when i run

### ISSUE THREAD

**Issue by ryanballer4life7** [outlaylol/Aria#20]
PS C:\Users\ryanb\Desktop\Aria-master> node .
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'enmap'
Require stack:
- C:\Users\ryanb\Desktop\Aria-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ryanb\Desktop\Aria-master\index.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\ryanb\\Desktop\\Aria-master\\index.js' ]
}

**Comment by Hexxx-Cmd** [comment]
My friend come on this is a stupid problem clearly your not a
developer however do this on console "npm i enmap"
